### ISSUE TITLE
To-do list 입력과 출력

### ISSUE THREAD

**Issue by mong-byte** [freeonboard-highfive/5_ModuCompany_team1#2]
- [ ] 입출력을 위한 UI 구현
- [ ] 각각의 To-do 아이템을 위한 마크업
- [ ] input을 입력 받아 각각의 To-do list 출력
