### ISSUE TITLE
해당 Todo Item의 상태 설정 

### ISSUE THREAD

**Issue by hurima90-kim** [freeonboard-highfive/5_ModuCompany_team1#5]
- [x] 상태설정 드롭다운 구현(Todo, Doing, Done)
- [x] 상태설정 기능 구현
- [x] 선택된 상태를 로컬스토리지에 저장 또는 변경
